<?php

namespace Container7s9vdlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealEstateExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Command\RealEstateExecutor' shared autowired service.
     *
     * @return \App\Command\RealEstateExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\console\\Command\\Command.php';
        include_once \dirname(__DIR__, 4).'\\src\\Command\\RealEstateExecutor.php';

        return $container->services['console.command.public_alias.App\\Command\\RealEstateExecutor'] = new \App\Command\RealEstateExecutor();
    }
}
