<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPBbxjGC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPBbxjGC/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPBbxjGC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPBbxjGC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPBbxjGC\App_KernelProdContainer([
    'container.build_hash' => 'PBbxjGC',
    'container.build_id' => '5f4f925a',
    'container.build_time' => 1602008725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPBbxjGC');
