<?php

namespace ContainerPBbxjGC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFibonacciCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\FibonacciCommand' shared autowired service.
     *
     * @return \App\Command\FibonacciCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\FibonacciCommand'] = $instance = new \App\Command\FibonacciCommand();

        $instance->setName('app:fibonacci');

        return $instance;
    }
}
