<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7s9vdlE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7s9vdlE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7s9vdlE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7s9vdlE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7s9vdlE\App_KernelDevDebugContainer([
    'container.build_hash' => '7s9vdlE',
    'container.build_id' => '2137f08a',
    'container.build_time' => 1602143074,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7s9vdlE');
